#!/usr/bin/env bash

pushd ~/workspace/github.com/thenameiswiiwin//dev/env/.config/nvim
git add .
git commit -m 'automated dev commit'
git push
popd

pushd ~/workspace/github.com/thenameiswiiwin/dev/tmux-sessionizer/
git add .
git commit -m 'automated dev commit'
git push
popd

pushd ~/dev
git add .
git commit -m 'automated dev commit'
git push
popd
