preload = /home/thenameiswiiwin/personal/wallwaper
preload = /home/thenameiswiiwin/personal/wallwaper
preload = /home/thenameiswiiwin/personal/wallwaper
wallpaper = ,/home/thenameiswiiwin/personal/wallwaper

